# Generated by Django 4.0.10 on 2023-12-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRelatedDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('starting_time', models.TimeField(blank=True, null=True)),
                ('installer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.installerdetail')),
            ],
        ),
    ]
